# Generated by Django 3.2.3 on 2021-05-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postlike',
            old_name='author',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='postlike',
            name='value',
            field=models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default=0, max_length=8),
            preserve_default=False,
        ),
    ]
